export default {
  // 'color.theme': 'dark',
  'color.theme': 'light',
  'color.background': '',
  // 'color.background': 'linear-gradient(153deg, rgba(106,137,184,1) 0%, rgba(57,18,111,1) 100%)',
  'color.surface': '',
  // 'color.surface': '33, 24, 46',
  'color.activeRowColor': '#C5CAE9',
  'color.waveform': 'rgb(106,137,184)',
  'color.activeWaveform': '#303F9F',
  // 'color.activeWaveform': 'rgb(250, 250, 250)',
  'color.activeTimeWindow': '#888888',
  'color.T0': 'orange',
  'color.TTT': '#0352fc',
  'color.TTTNLL': '#0000ff',
  'color.pickAutomatic': '#ff0000',
  'color.pickManual': '#008000',
  'color.additionalPickAutomatic': '#c94b4b',
  'color.additionalPickManual': '#537a53',
  'color.detector': '#7303fc',
  'color.spectrogram': 'VIRIDIS',
  'picker.spectrogramHeight': 80,
  'picker.pickerWaveformHeight': 120,
  'picker.listWaveformHeight': 40,
  'picker.listMode': 'line',
  'detector.model': 'phasenet',
  'detector.pThreshold': 0.3,
  'detector.sThreshold': 0.3,
  'keybinding.setPhaseP': 'w',
  'keybinding.setPhaseS': 's',
  'keybinding.alignToOrigin': 'alt+o',
  'keybinding.alignToP': 'alt+w',
  'keybinding.alignToS': 'alt+s',
  'keybinding.toggleFilter': 'f',
  'keybinding.toggleDenoiser': 'shift+d',
  'keybinding.toggleSpectrogram': 'h',
  'keybinding.toggleRotation': 'z',
  'keybinding.createPick': 'space',
  'keybinding.deletePick': 'delete',
  'keybinding.polarityPositive': 'shift+up',
  'keybinding.polarityNegative': 'shift+down',
  'keybinding.resetPolarity': 'escape',
  'keybinding.nextStation': 'a',
  'keybinding.prevStation': 'q',
  'keybinding.relocate': 'alt+r',
  'keybinding.computeMagnitudes': 'alt+m',
  'keybinding.commit': 'alt+c',
  'keybinding.togglePicker': 'alt+shift+p',
  'miscellaneous.longitudeReference': 166,
  'miscellaneous.maxTrace': 100,
  'miscellaneous.defaultRadius': 1,
  'miscellaneous.timewindow1': 15,
  'miscellaneous.timewindow2': 30,
  'filter': [
    { name: 'HP 1', expression: 'highpass(4, 1)' },
    { name: 'BP 0.5-8', expression: 'bandpass(4, 0.5, 8)' },
    { name: 'BP 1-8', expression: 'bandpass(4, 1, 8)' },
    { name: 'BP 1-10', expression: 'bandpass(4, 1, 10)' },
    { name: 'BP 1-50', expression: 'bandpass(4, 1, 50)' },
    { name: 'BP 2-10', expression: 'bandpass(4, 2, 10)' },
    { name: 'BP 2-20', expression: 'bandpass(4, 2, 20)' },
    { name: 'BP 4-20', expression: 'bandpass(4, 4, 20)' },
    { name: 'LP 4', expression: 'lowpass(4, 4)' },
    { name: 'LP 10', expression: 'lowpass(4, 10)' },
    { name: 'LP 25', expression: 'lowpass(4, 25)' }
  ]
} as Record<string, any>