import { WebpickerSettings } from './types'

const settings: WebpickerSettings = {
  themeDark: false,
  'picker.filters': [
    { name: 'HP 1', type: 'highpass', fc: 1, order: 4 },
    { name: 'BP 0.5-8', type: 'bandpass', fc: [0.5, 8], order: 4 },
    { name: 'BP 1-8', type: 'bandpass', fc: [1, 8], order: 4 },
    { name: 'BP 1-10', type: 'bandpass', fc: [1, 10], order: 4 },
    { name: 'BP 1-50', type: 'bandpass', fc: [1, 50], order: 4 },
    { name: 'BP 2-10', type: 'bandpass', fc: [2, 10], order: 4 },
    { name: 'BP 2-20', type: 'bandpass', fc: [2, 20], order: 4 },
    { name: 'BP 4-20', type: 'bandpass', fc: [4, 20], order: 4 },
    { name: 'LP 4', type: 'lowpass', fc: 4, order: 4 },
    { name: 'LP 10', type: 'lowpass', fc: 10, order: 4 },
    { name: 'LP 25', type: 'lowpass', fc: 25, order: 4 }
  ],
  'pickerProgressBar.size': 3,
  'pickerProgressBar.color': '#ffffff',
  'darkPickerColor.background': 'rgba(37, 37, 37, 1)',
  'darkPickerColor.backgroundEven': 'rgba(45, 45, 45, 1)',
  'darkPickerColor.line': '#57c3ff',
  'darkPickerColor.lineBar': '#ffffff',
  'darkPickerColor.text': '#888888',
  'darkPickerColor.selected': 'rgba(73, 89, 98, 1)',
  'solirizedPickerColor.automatic': '#dc322f',
  'solirizedPickerColor.avgLine': 'rgba(7,54,66,0.4)',
  'solirizedPickerColor.background': 'rgba(0,43,54,1)',
  'solirizedPickerColor.backgroundEven': 'rgba(7,54,66,1)',
  'solirizedPickerColor.grid': 'rgba(88,110,117,0.3)',
  'solirizedPickerColor.line': '#268BD2',
  'solirizedPickerColor.lineBar': '#ffffff',
  'solirizedPickerColor.manual': '#2aa198',
  'solirizedPickerColor.selected': 'rgba(88,110,117,1)',
  'solirizedPickerColor.theoretical': '#6c71c4',
  'pickerColor.amplitudeValue': '#808080',
  'pickerColor.background': 'rgba(255, 255, 255, 1)',
  'pickerColor.backgroundEven': 'rgba(229, 238, 241, 1)',
  'pickerColor.grid': 'rgba(180,180,180,.3)',
  'pickerColor.selected': 'rgba(200, 231, 249, 1)',
  'pickerColor.selectedWindow': 'rgba(0, 0, 0, 0.1)',
  'pickerColor.border': '#000000',
  'pickerColor.text': '#000000',
  'pickerColor.labelBackground': 'rgba(75, 75, 75, 0.8)',
  'pickerColor.labelText': '#ffffff',
  'pickerColor.line': '#9cb9c9',
  'pickerColor.lineBar': '#000000',
  'pickerColor.avgLine': 'rgba(180,180,180,.3)',
  'pickerColor.theoretical': '#0000ff',
  'pickerColor.automatic': '#ff0000',
  'pickerColor.manual': '#1ab11b',
  'pickerColor.phasenet': '#ff00ff',
  'pickerSize.pickerWaveformHeight': 120,
  'pickerSize.listWaveformHeight': 40,
  'pickerSize.listWaveformWrapperHeight': 400,
  'pickerKeybinding.nextStation': 'down',
  'pickerKeybinding.previousStation': 'up',
  'pickerKeybinding.setPolarityPositive': 'shift+up',
  'pickerKeybinding.setPolarityNegative': 'shift+down',
  'pickerKeybinding.setNoPolarity': 'escape',
  'pickerKeybinding.leavePickingMode': 'escape',
  'pickerKeybinding.setPickerPhaseP': 'p',
  'pickerKeybinding.setPickerPhaseS': 's',
  'pickerKeybinding.deletePick': 'backspace',
  'pickerKeybinding.alignToOrigin': 'alt+o',
  'pickerKeybinding.alignToP': 'alt+p',
  'pickerKeybinding.alignToS': 'alt+s',
  'pickerKeybinding.toggleFilter': 'f',
  'pickerKeybinding.toggleEqualScale': '=',
  'pickerKeybinding.createPick': 'space',
  'pickerKeybinding.movePickLineRight': 'right',
  'pickerKeybinding.moveFastPickLineRight': 'shift+right',
  'pickerKeybinding.movePickLineLeft': 'left',
  'pickerKeybinding.moveFastPickLineLeft': 'shift+left',
  'pickerKeybinding.xZoomIn': 'shift+>',
  'pickerKeybinding.xZoomOut': 'shift+<',
  'pickerKeybinding.yZoomIn': 'shift+y',
  'pickerKeybinding.yZoomOut': 'y',
  'pickerKeybinding.setFocusComponentZ': 'z',
  'pickerKeybinding.setFocusComponentN': 'n',
  'pickerKeybinding.setFocusComponentE': 'e',
  'pickerKeybinding.setTimeUncertainty0': 'shift+0',
  'pickerKeybinding.setTimeUncertainty1': 'shift+1',
  'pickerKeybinding.setTimeUncertainty2': 'shift+2',
  'pickerKeybinding.setTimeUncertainty3': 'shift+3',
  'pickerKeybinding.setTimeUncertainty4': 'shift+4',
  'pickerKeybinding.setTimeUncertainty5': 'shift+5',
  'pickerKeybinding.setTimeUncertainty6': 'shift+6',
  'pickerKeybinding.setTimeUncertainty7': 'shift+7',
  'pickerKeybinding.setTimeUncertainty8': 'shift+8',
  'pickerKeybinding.setTimeUncertainty9': 'shift+9'
}

export default settings
